apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: app-test-1
  namespace: argocd
  finalizers:
    # The default behaviour is foreground cascading deletion
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: 'https://github.com/darkhonor/argotest.git'
    path: app-test-1
    targetRevision: HEAD
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: app-test-1
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - PruneLast=true
